#!/usr/bin/env python3
"""`python -m cdt.honcho_setup` — choose the Honcho reasoning provider.

The provider that powers Honcho's background reasoning (deriver + dialectic +
summary) is **not baked in** — you pick it at install time. This writes
`infra/honcho/.env` for the chosen provider; any OpenAI-compatible endpoint
works (OpenAI, DeepSeek, OpenRouter, local Ollama/vLLM…), plus native Anthropic.

  python -m cdt.honcho_setup                         # interactive
  python -m cdt.honcho_setup --provider deepseek     # non-interactive
  python -m cdt.honcho_setup --provider ollama       # local, no key needed
  python -m cdt.honcho_setup --provider openai --model gpt-4o --api-key sk-...
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional

from .project import force_utf8

from .project import PACKAGE_INFRA

FEATURES = ("DERIVER", "DIALECTIC", "SUMMARY")

# Each preset is OpenAI-compatible unless transport says otherwise. base_url
# empty = use the provider's native default.
PRESETS: Dict[str, dict] = {
    "openai": {"transport": "openai", "base_url": "https://api.openai.com/v1",
               "model": "gpt-4o-mini", "key_env": "LLM_OPENAI_API_KEY",
               "needs_key": True},
    "deepseek": {"transport": "openai", "base_url": "https://api.deepseek.com/v1",
                 "model": "deepseek-chat", "key_env": "LLM_OPENAI_API_KEY",
                 "needs_key": True},
    "openrouter": {"transport": "openai", "base_url": "https://openrouter.ai/api/v1",
                   "model": "google/gemini-2.5-flash", "key_env": "LLM_OPENAI_API_KEY",
                   "needs_key": True},
    "ollama": {"transport": "openai", "base_url": "http://host.docker.internal:11434/v1",
               "model": "llama3.1", "key_env": "LLM_OPENAI_API_KEY",
               "needs_key": False},  # local: any dummy key
    "anthropic": {"transport": "anthropic", "base_url": "",
                  "model": "claude-haiku-4-5", "key_env": "LLM_ANTHROPIC_API_KEY",
                  "needs_key": True},
}


def render_env(provider: str, model: str, base_url: str, api_key: str,
               key_env: str, transport: str) -> str:
    lines: List[str] = [
        f"# Honcho reasoning provider: {provider} (generated by cdt.honcho_setup).",
        "# Re-run `python -m cdt.honcho_setup` to switch providers.",
        "",
        f"{key_env}={api_key}",
        "",
    ]
    for feat in FEATURES:
        lines.append(f"{feat}_MODEL_CONFIG__TRANSPORT={transport}")
        lines.append(f"{feat}_MODEL_CONFIG__MODEL={model}")
        if base_url:
            lines.append(f"{feat}_MODEL_CONFIG__OVERRIDES__BASE_URL={base_url}")
        lines.append("")
    lines.append("# Self-host: no auth (the API binds to localhost only).")
    lines.append("AUTH_USE_AUTH=false")
    return "\n".join(lines) + "\n"


def _prompt_choice() -> str:
    names = list(PRESETS)
    print("Choose the Honcho reasoning provider:")
    for i, name in enumerate(names, 1):
        p = PRESETS[name]
        loc = "local" if name == "ollama" else (p["base_url"] or "native")
        print(f"  {i}. {name:<11} ({p['model']}, {loc})")
    raw = input(f"Provider [1-{len(names)}] (default 1): ").strip()
    if not raw:
        return names[0]
    if raw.isdigit() and 1 <= int(raw) <= len(names):
        return names[int(raw) - 1]
    if raw in PRESETS:
        return raw
    print(f"Unknown choice '{raw}'.", file=sys.stderr)
    raise SystemExit(2)


def main(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(description="Configure Honcho's reasoning provider.")
    ap.add_argument("--provider", choices=list(PRESETS), help="provider preset")
    ap.add_argument("--model", help="override the model id")
    ap.add_argument("--base-url", help="override the OpenAI-compatible base URL")
    ap.add_argument("--api-key", help="API key (or set it later in the .env)")
    ap.add_argument("--out", type=Path, default=None,
                    help="output .env path (default: the staged Honcho infra dir)")
    ap.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = ap.parse_args(argv)
    force_utf8()

    out = args.out or (PACKAGE_INFRA / "honcho" / ".env")

    provider = args.provider or _prompt_choice()
    preset = PRESETS[provider]
    model = args.model or preset["model"]
    base_url = preset["base_url"] if args.base_url is None else args.base_url
    transport = preset["transport"]
    key_env = preset["key_env"]

    api_key = args.api_key
    if api_key is None:
        if preset["needs_key"]:
            if sys.stdin.isatty():
                api_key = input(f"{provider} API key (blank = fill in later): ").strip()
            api_key = api_key or f"set-your-{provider}-key"
        else:
            api_key = "ollama"  # local: any value

    if out.exists() and not args.force:
        print(f"{out} exists (use --force to overwrite).", file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_env(provider, model, base_url, api_key, key_env, transport),
                   encoding="utf-8")

    print(f"Wrote {out} (provider: {provider}, model: {model}).")
    print(f"  Honcho infra staged at: {out.parent}  (run `docker compose up -d` there)")
    if api_key.startswith("set-your-"):
        print(f"  -> edit {out} and set {key_env} before `docker compose up`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
