#!/usr/bin/env python3
"""`cdt init|sync` — generate and keep alive a project's Claude-Code config.

`init` scaffolds, into the target project:
  .claude/agents/<role>.md          a relevant subset of role Agents
  .claude/skills/<skill>/SKILL.md   the matching Skills
  .cdt/config.json                  enrollment (slug, type, roles, Honcho workspace)
  .cdt/stack/<TYPE>.md              detected technologies (RAG-steering)
  .cdt/memory/                      project memory tree (diary/docs/records/refs)
  CLAUDE.md                         project guide (roles + memory + 12-gate flow)

`sync` keeps CLAUDE.md **live**: it re-detects the stack, refreshes the roles,
and pulls the latest diary memory — regenerating only the managed region
(between markers) and preserving anything the human wrote below it.
"""
from __future__ import annotations

import argparse
import datetime
import json
import shutil
import sys
from pathlib import Path
from typing import List, Optional

from . import roles as roles_mod
from . import targets as targets_mod
from .detect import VALID_TYPES, detect, profile
from .honcho_client import DEFAULT_BASE_URL as DEFAULT_HONCHO_URL
from .targets import GuideContext
from .project import (cdt_dir, config_path, debug_trace, diary_dir,
                      find_project_root, force_utf8, memory_dir, read_config,
                      register_project, slugify, stack_dir, write_config)

# The per-project memory tree (relative to `.cdt/memory/`): leaf dir -> purpose.
# `diary/` and `daily/` are local-only (git-ignored); everything else is
# committed knowledge. `refs/` is pointers, never ingested by Honcho.
MEMORY_TREE = {
    "diary": "Append-only machine diary (JSONL, one file per day). Source of truth.",
    "daily": "Human-readable daily digests, generated from `diary/`.",
    "docs/architecture": "Living architecture snapshots (overview, backend, frontend, integrations, tech-debt).",
    "docs/api": "API surface and endpoints.",
    "docs/database": "Schema and data model.",
    "docs/operations": "Runbooks and operational notes.",
    "docs/end-user": "End-user facing documentation.",
    "records/bugs": "Dated bug records (`YYYY-MM-DD-slug.md`).",
    "records/decisions": "Architecture Decision Records (`ADR-NNN-slug.md`).",
    "records/discovery": "Discovery / grilling sessions.",
    "records/features": "Feature specs per sprint.",
    "records/gaps": "Known gaps and overrides.",
    "refs/jira": "Pointers to Jira issues (not ingested by Honcho).",
    "refs/prd": "Pointers to PRDs (not ingested).",
    "refs/sql": "SQL migration references (not ingested).",
    "refs/imgs": "Image references (not ingested).",
}
# Local-only (git-ignored) under `.cdt/`: the machine diary and the generated
# digests. `docs/`, `records/` and `refs/` are meant to be committed.
MEMORY_LOCAL = ("memory/diary/", "memory/daily/", "memory/.ingest.json",
                "memory/.observations.jsonl")


def _scaffold_memory_tree(project: Path) -> int:
    """Create `.cdt/memory/` and its leaf dirs, each seeded with an `_index.md`.

    The `_index.md` stub both documents the folder's purpose and keeps the
    (otherwise empty) directory tracked by git. Idempotent: never overwrites an
    `_index.md` a human may have edited. Returns the number of leaves created.
    """
    root = memory_dir(project)
    root.mkdir(parents=True, exist_ok=True)
    created = 0
    for rel, purpose in MEMORY_TREE.items():
        leaf = root / rel
        leaf.mkdir(parents=True, exist_ok=True)
        idx = leaf / "_index.md"
        if not idx.is_file():
            title = rel.split("/")[-1].replace("-", " ").title()
            idx.write_text(f"# {title}\n\n{purpose}\n", encoding="utf-8")
            created += 1
    _write_memory_index(project)
    return created


def _write_memory_index(project: Path) -> None:
    """Regenerate `memory/_index.md` — a live map of what each folder holds.

    Lists the real files per folder (excluding `_index.md` stubs) and marks the
    ones already ingested into Honcho (per the `.ingest.json` manifest). `refs/`
    files are shown but flagged as never-ingested.
    """
    mem = memory_dir(project)
    manifest: dict = {}
    mp = mem / ".ingest.json"
    if mp.is_file():
        try:
            data = json.loads(mp.read_text(encoding="utf-8"))
            manifest = data if isinstance(data, dict) else {}
        except (ValueError, OSError):
            manifest = {}

    lines = ["# Project memory", "",
             "Conductor's per-project memory tree. Three natures:", "",
             "- `diary/` — append-only machine events (local, git-ignored).",
             "- `docs/` + `records/` — living knowledge, ingested into Honcho.",
             "- `refs/` — pointers to external systems (never ingested).", "",
             "_Generated by `cdt init|sync`; edits are overwritten._", ""]
    for rel, purpose in MEMORY_TREE.items():
        folder = mem / rel
        files = sorted(p for p in folder.rglob("*")
                       if p.is_file() and p.name != "_index.md") if folder.is_dir() else []
        lines.append(f"### `{rel}/`")
        lines.append(f"{purpose}")
        if not files:
            lines.append("- _(empty)_")
        for p in files:
            r = p.relative_to(mem).as_posix()
            if rel in ("diary", "daily"):
                mark = " — local"
            elif rel.startswith("refs/"):
                mark = " — ref"
            elif r in manifest:
                mark = " — ✓ ingested"
            else:
                mark = " — pending ingest"
            lines.append(f"- `{p.name}`{mark}")
        lines.append("")
    (mem / "_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _migrate_legacy_diary(project: Path) -> int:
    """One-time move of a pre-0.2.20 diary (`.cdt/journal/`) into `memory/diary/`.

    Moves files (preserving history, never renaming `.jsonl`); skips any name
    that already exists at the destination; removes the old folder if it ends
    up empty. Returns the number of files moved.
    """
    old = cdt_dir(project) / "journal"
    new = diary_dir(project)
    if not old.is_dir() or old.resolve() == new.resolve():
        return 0
    new.mkdir(parents=True, exist_ok=True)
    moved = 0
    for jf in old.glob("*.jsonl"):
        dest = new / jf.name
        if dest.exists():
            continue
        shutil.move(str(jf), str(dest))
        moved += 1
    try:                              # drop the old dir only if nothing is left
        old.rmdir()
    except OSError:
        pass
    return moved


def _auto_memory_sync(root: Path, config: dict) -> None:
    """Best-effort: digest today's diary and ingest changed docs/records.

    Wraps the `journal` commands so `cdt sync` keeps Honcho and the digests
    current. Never raises into sync — Honcho being down only means the diary's
    local mirror and manifest stay the source of truth.
    """
    try:
        from . import journal
        journal.cmd_digest(root, config, argparse.Namespace(all=False, session=None))
        journal.cmd_ingest(root, config, argparse.Namespace(force=False))
    except Exception:  # noqa: BLE001 — Honcho down only means the local mirror stays SoT
        debug_trace("_auto_memory_sync")


def _ensure_memory_gitignore(project: Path) -> None:
    """Make sure `.cdt/.gitignore` keeps the local diary/digests untracked.

    Merges the required patterns into any existing file (preserving the human's
    lines and the legacy `journal/` entry) instead of clobbering it.
    """
    gi = cdt_dir(project) / ".gitignore"
    existing = gi.read_text(encoding="utf-8").splitlines() if gi.is_file() else []
    have = {ln.strip() for ln in existing}
    extra = [ln for ln in MEMORY_LOCAL if ln not in have]
    if not extra:
        return
    merged = [*existing, *extra] if existing else extra
    gi.write_text("\n".join(merged) + "\n", encoding="utf-8")

# --- rendering ---------------------------------------------------------------

def _stack_md(ptype: str, techs: List[str], evidence: List[str],
              prof: Optional[dict] = None) -> str:
    prof = prof or {}
    ev = ", ".join(evidence) if evidence else "none"
    tags = ", ".join(techs) if techs else "none"

    def line(label: str, key: str) -> str:
        items = prof.get(key) or []
        body = ", ".join(items) if items else "_(not detected — complete manually)_"
        return f"- **{label}:** {body}"

    detected = "\n".join((
        line("Languages & versions", "languages"),
        line("Frameworks", "frameworks"),
        line("Datastore(s)", "datastores"),
        line("Build / package manager", "build"),
        line("Testing", "testing"),
        line("Tooling (lint / format / containers)", "tooling"),
        line("Notable libraries", "libraries"),
    ))
    return f"""# Stack — {ptype}

Technologies this project uses. Agents read this so their `cdt library`
(RAG) queries are **project-aware**. Auto-filled from the manifests by
`cdt init/sync`; refine anything marked _not detected_.

## Detected
{detected}

## To complete (owner / Conductor)
- Architecture notes / constraints:
- External integrations / APIs:

<!-- detected tags: {tags} -->
<!-- detection evidence: {ev} -->
"""


# --- scaffolding -------------------------------------------------------------


def _resolve_selection(ptype: str, all_roles: bool, override: Optional[List[str]]):
    """Returns (selected, mode)."""
    if override:
        return roles_mod.select_roles(ptype, override=override), "custom"
    if all_roles:
        return roles_mod.select_roles(ptype, all_roles=True), "all"
    return roles_mod.select_roles(ptype), "subset"


def _config_targets(root: Path, config: dict):
    """The targets configured for a project: the persisted `targets` keys, or
    (back-compat for pre-multi-harness configs) auto-detect / default."""
    keys = config.get("targets")
    if keys:
        try:
            return [targets_mod.get(k) for k in keys]
        except KeyError:
            pass
    return targets_mod.resolve(None, root)


def _emit_targets(root: Path, tgts, selected: List[str], *,
                  ptype: str = "", mode: str = "", verbose: bool = False) -> int:
    """Emit roles + the `/cdt` driver + live-memory hooks for each target.

    Shared by `init` (verbose: prints per-target detail) and `sync` (silent
    refresh). Returns the per-target role count (all targets emit the same set).
    """
    n = 0
    for t in tgts:
        n = t.emit_roles(root, selected)
        drv = t.emit_driver(root)
        hooks = t.emit_hooks(root)
        autos = t.emit_automations(root)
        mcps = t.emit_mcp(root)
        if verbose:
            print(f"[2/4] {t.label}: {n} agents + {n} skills ({mode} for {ptype})"
                  + (" + /cdt driver" if drv else "")
                  + (f" + {hooks} live-memory hook(s)" if hooks else "")
                  + (f" + {autos} automation(s)" if autos else "")
                  + (f" + {mcps} MCP file(s)" if mcps else ""))
    return n


def _write_stack_file(root: Path, ptype: str, techs: List[str],
                      evidence: List[str], prof: Optional[dict]) -> None:
    """Write `.cdt/stack/<TYPE>.md` from the detection result (idempotent)."""
    sd = stack_dir(root)
    sd.mkdir(parents=True, exist_ok=True)
    (sd / f"{ptype}.md").write_text(
        _stack_md(ptype, techs, evidence, prof), encoding="utf-8")


def refresh_claude_md(root: Path) -> bool:
    """Best-effort live refresh of each target's guide (called after journal writes).

    Only refreshes guides that already exist — a journal write never creates a
    guide that the human removed.
    """
    config = read_config(root)
    if config is None:
        return False
    selected = config.get("roles") or roles_mod.select_roles(config.get("type", "unknown"))
    ctx = GuideContext(root, config.get("project", root.name),
                       config.get("type", "unknown"), selected)
    ok = False
    for t in _config_targets(root, config):
        if not t.guide_path(root).is_file():
            continue
        try:
            t.emit_guide(ctx)
            ok = True
        except Exception:  # noqa: BLE001 — refresh is best-effort
            debug_trace(f"refresh_claude_md:{t.key}")
    return ok


# --- commands ----------------------------------------------------------------

def cmd_init(args) -> int:
    project = Path(args.path).resolve()
    if not project.is_dir():
        print(f"ERROR: not a directory: {project}", file=sys.stderr)
        return 2
    if config_path(project).is_file() and not args.force:
        print(f"Already enrolled: {config_path(project)} "
              "(use --force to re-init, or `cdt sync` to refresh)")
        return 0

    det_type, techs, evidence = detect(project)
    prof = profile(project)
    ptype = args.type or det_type
    slug = slugify(args.name or project.name)
    override = [s.strip() for s in args.roles.split(",")] if args.roles else None
    try:
        selected, mode = _resolve_selection(ptype, args.all, override)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    try:
        tgts = targets_mod.resolve(args.target, project)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    print(f"[1/4] analyzing {project.name}: type={ptype}"
          + (f", detected={', '.join(techs)}" if techs else "")
          + f" -> {', '.join(t.label for t in tgts)}")
    _emit_targets(project, tgts, selected, ptype=ptype, mode=mode, verbose=True)

    leaves = _scaffold_memory_tree(project)
    _write_stack_file(project, ptype, techs, evidence, prof)
    _ensure_memory_gitignore(project)
    write_config(project, {
        "project": slug, "type": ptype, "roles": selected, "roles_mode": mode,
        "targets": [t.key for t in tgts],
        "honcho": {"workspace": slug, "base_url": args.honcho_url,
                   "session_prefix": "cdt"},
        "created": datetime.date.today().isoformat(),
    })
    register_project(project, slug, ptype)
    print(f"[3/4] .cdt/: enrolled '{slug}', stack -> {ptype}.md, "
          f"memory tree -> {leaves} folders")
    ctx = GuideContext(project, slug, ptype, selected)
    for t in tgts:
        state = t.emit_guide(ctx)
        print(f"[4/4] {t.label} guide {state} "
              f"({len(selected)} roles + memory + 12-gate flow)")
    print("Done. `cdt sync` keeps the guide(s) live as the project evolves.")
    return 0


def cmd_sync(args) -> int:
    root = Path(args.path).resolve() if args.path else find_project_root()
    config = read_config(root)
    if config is None:
        print(f"ERROR: not an enrolled project (no .cdt/ at {root}). "
              "Run `cdt init` first.", file=sys.stderr)
        return 2

    slug = config.get("project", slugify(root.name))
    mode = config.get("roles_mode", "subset")
    det_type, techs, evidence = detect(root)
    prof = profile(root)
    ptype = args.type or (det_type if det_type != "unknown" else config.get("type", "unknown"))

    if mode == "all":
        selected = roles_mod.select_roles(ptype, all_roles=True)
    elif mode == "custom":
        selected = config.get("roles") or roles_mod.select_roles(ptype)
    else:
        selected = roles_mod.select_roles(ptype)  # subset re-computed for current type

    # `--target` overrides the persisted set; else re-emit the configured ones.
    if getattr(args, "target", None):
        try:
            tgts = targets_mod.resolve(args.target, root)
        except ValueError as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2
    else:
        tgts = _config_targets(root, config)

    n = _emit_targets(root, tgts, selected)  # roles + /cdt driver + live-memory hooks
    leaves = _scaffold_memory_tree(root)  # ensure/upgrade the memory tree (idempotent)
    _ensure_memory_gitignore(root)
    migrated = _migrate_legacy_diary(root)  # pre-0.2.20 journal/ -> memory/diary/
    _write_stack_file(root, ptype, techs, evidence, prof)
    config.update({"type": ptype, "roles": selected, "roles_mode": mode,
                   "targets": [t.key for t in tgts]})
    write_config(root, config)
    register_project(root, slug, ptype)
    _auto_memory_sync(root, config)   # digest + ingest changed docs/records
    _write_memory_index(root)         # refresh the live map post-ingest
    ctx = GuideContext(root, slug, ptype, selected)
    states = {t.label: t.emit_guide(ctx) for t in tgts}

    tree_note = f", memory tree +{leaves} folders" if leaves else ""
    mig_note = f", migrated {migrated} legacy diary file(s)" if migrated else ""
    guides = ", ".join(f"{label} {state}" for label, state in states.items())
    print(f"synced '{slug}' (type={ptype}, {n} roles, "
          f"targets={','.join(t.key for t in tgts)}): stack refreshed, "
          f"diary memory pulled{tree_note}{mig_note}, {guides}.")
    return 0


def main(argv: List[str]) -> int:
    force_utf8()
    # Dispatched as `cdt init ...` / `cdt sync ...`; the
    # action word is argv[0] when present, else default to init.
    action = "init"
    rest = argv
    if argv and argv[0] in ("init", "sync"):
        action, rest = argv[0], argv[1:]

    ap = argparse.ArgumentParser(prog=f"cdt {action}")
    ap.add_argument("path", nargs="?", default=None if action == "sync" else ".",
                    help="project directory")
    ap.add_argument("--type", choices=VALID_TYPES, help="force the project type")
    ap.add_argument("--target",
                    help="harness target(s): comma list of "
                         f"{{{','.join(targets_mod.available())},all}} "
                         "(default: auto-detect, else claude)")
    if action == "init":
        ap.add_argument("--name", help="project name (default: directory name)")
        ap.add_argument("--all", action="store_true", help="scaffold all 36 roles")
        ap.add_argument("--roles", help="comma-separated role slugs (override the subset)")
        ap.add_argument("--honcho-url", default=DEFAULT_HONCHO_URL, help="Honcho base URL")
        ap.add_argument("--force", action="store_true", help="re-init (overwrite)")
    args = ap.parse_args(rest)

    return cmd_sync(args) if action == "sync" else cmd_init(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
