#!/usr/bin/env python3
"""`cdt init|sync` — generate and keep alive a project's Claude-Code config.

`init` scaffolds, into the target project:
  .claude/agents/<role>.md          a relevant subset of role Agents
  .claude/skills/<skill>/SKILL.md   the matching Skills
  .cdt/config.json                  enrollment (slug, type, roles, Honcho workspace)
  .cdt/stack/<TYPE>.md              detected technologies (RAG-steering)
  .cdt/memory/                      project memory tree (diary/docs/records/refs)
  CLAUDE.md                         project guide (roles + memory + 11-gate flow)

`sync` keeps CLAUDE.md **live**: it re-detects the stack, refreshes the roles,
and pulls the latest diary memory — regenerating only the managed region
(between markers) and preserving anything the human wrote below it.
"""
from __future__ import annotations

import argparse
import datetime
import json
import shutil
import sys
from pathlib import Path
from typing import List, Optional

from . import roles as roles_mod
from .detect import VALID_TYPES, detect, profile
from .project import (cdt_dir, config_path, diary_dir, find_project_root,
                      force_utf8, journal_dir, memory_dir, read_config,
                      register_project, slugify, stack_dir, write_config)

TEMPLATES = Path(__file__).resolve().parent / "templates"
DEFAULT_HONCHO_URL = "http://localhost:8000"

# The per-project memory tree (relative to `.cdt/memory/`): leaf dir -> purpose.
# `diary/` and `daily/` are local-only (git-ignored); everything else is
# committed knowledge. `refs/` is pointers, never ingested by Honcho.
MEMORY_TREE = {
    "diary": "Append-only machine diary (JSONL, one file per day). Source of truth.",
    "daily": "Human-readable daily digests, generated from `diary/`.",
    "docs/architecture": "Living architecture snapshots (overview, backend, frontend, integrations, tech-debt).",
    "docs/api": "API surface and endpoints.",
    "docs/database": "Schema and data model.",
    "docs/operations": "Runbooks and operational notes.",
    "docs/end-user": "End-user facing documentation.",
    "records/bugs": "Dated bug records (`YYYY-MM-DD-slug.md`).",
    "records/decisions": "Architecture Decision Records (`ADR-NNN-slug.md`).",
    "records/discovery": "Discovery / grilling sessions.",
    "records/features": "Feature specs per sprint.",
    "records/gaps": "Known gaps and overrides.",
    "refs/jira": "Pointers to Jira issues (not ingested by Honcho).",
    "refs/prd": "Pointers to PRDs (not ingested).",
    "refs/sql": "SQL migration references (not ingested).",
    "refs/imgs": "Image references (not ingested).",
}
# Local-only (git-ignored) under `.cdt/`: the machine diary and the generated
# digests. `docs/`, `records/` and `refs/` are meant to be committed.
MEMORY_LOCAL = ("memory/diary/", "memory/daily/", "memory/.ingest.json")


def _scaffold_memory_tree(project: Path) -> int:
    """Create `.cdt/memory/` and its leaf dirs, each seeded with an `_index.md`.

    The `_index.md` stub both documents the folder's purpose and keeps the
    (otherwise empty) directory tracked by git. Idempotent: never overwrites an
    `_index.md` a human may have edited. Returns the number of leaves created.
    """
    root = memory_dir(project)
    root.mkdir(parents=True, exist_ok=True)
    created = 0
    for rel, purpose in MEMORY_TREE.items():
        leaf = root / rel
        leaf.mkdir(parents=True, exist_ok=True)
        idx = leaf / "_index.md"
        if not idx.is_file():
            title = rel.split("/")[-1].replace("-", " ").title()
            idx.write_text(f"# {title}\n\n{purpose}\n", encoding="utf-8")
            created += 1
    _write_memory_index(project)
    return created


def _write_memory_index(project: Path) -> None:
    """Regenerate `memory/_index.md` — a live map of what each folder holds.

    Lists the real files per folder (excluding `_index.md` stubs) and marks the
    ones already ingested into Honcho (per the `.ingest.json` manifest). `refs/`
    files are shown but flagged as never-ingested.
    """
    mem = memory_dir(project)
    manifest: dict = {}
    mp = mem / ".ingest.json"
    if mp.is_file():
        try:
            data = json.loads(mp.read_text(encoding="utf-8"))
            manifest = data if isinstance(data, dict) else {}
        except (ValueError, OSError):
            manifest = {}

    lines = ["# Project memory", "",
             "Conductor's per-project memory tree. Three natures:", "",
             "- `diary/` — append-only machine events (local, git-ignored).",
             "- `docs/` + `records/` — living knowledge, ingested into Honcho.",
             "- `refs/` — pointers to external systems (never ingested).", "",
             "_Generated by `cdt init|sync`; edits are overwritten._", ""]
    for rel, purpose in MEMORY_TREE.items():
        folder = mem / rel
        files = sorted(p for p in folder.rglob("*")
                       if p.is_file() and p.name != "_index.md") if folder.is_dir() else []
        lines.append(f"### `{rel}/`")
        lines.append(f"{purpose}")
        if not files:
            lines.append("- _(empty)_")
        for p in files:
            r = p.relative_to(mem).as_posix()
            if rel in ("diary", "daily"):
                mark = " — local"
            elif rel.startswith("refs/"):
                mark = " — ref"
            elif r in manifest:
                mark = " — ✓ ingested"
            else:
                mark = " — pending ingest"
            lines.append(f"- `{p.name}`{mark}")
        lines.append("")
    (mem / "_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _migrate_legacy_diary(project: Path) -> int:
    """One-time move of a pre-0.2.20 diary (`.cdt/journal/`) into `memory/diary/`.

    Moves files (preserving history, never renaming `.jsonl`); skips any name
    that already exists at the destination; removes the old folder if it ends
    up empty. Returns the number of files moved.
    """
    old = cdt_dir(project) / "journal"
    new = diary_dir(project)
    if not old.is_dir() or old.resolve() == new.resolve():
        return 0
    new.mkdir(parents=True, exist_ok=True)
    moved = 0
    for jf in old.glob("*.jsonl"):
        dest = new / jf.name
        if dest.exists():
            continue
        shutil.move(str(jf), str(dest))
        moved += 1
    try:                              # drop the old dir only if nothing is left
        old.rmdir()
    except OSError:
        pass
    return moved


def _auto_memory_sync(root: Path, config: dict) -> None:
    """Best-effort: digest today's diary and ingest changed docs/records.

    Wraps the `journal` commands so `cdt sync` keeps Honcho and the digests
    current. Never raises into sync — Honcho being down only means the diary's
    local mirror and manifest stay the source of truth.
    """
    try:
        from . import journal
        journal.cmd_digest(root, config, argparse.Namespace(all=False, session=None))
        journal.cmd_ingest(root, config, argparse.Namespace(force=False))
    except Exception:  # noqa: BLE001
        pass


def _ensure_memory_gitignore(project: Path) -> None:
    """Make sure `.cdt/.gitignore` keeps the local diary/digests untracked.

    Merges the required patterns into any existing file (preserving the human's
    lines and the legacy `journal/` entry) instead of clobbering it.
    """
    gi = cdt_dir(project) / ".gitignore"
    existing = gi.read_text(encoding="utf-8").splitlines() if gi.is_file() else []
    have = {ln.strip() for ln in existing}
    extra = [ln for ln in MEMORY_LOCAL if ln not in have]
    if not extra:
        return
    merged = [*existing, *extra] if existing else extra
    gi.write_text("\n".join(merged) + "\n", encoding="utf-8")

MANAGED_START = "<!-- conductor:managed:start"
MANAGED_END = "<!-- conductor:managed:end -->"
MEMORY_KINDS = ("decision", "solution", "error", "plan")
MEMORY_LIMIT = 15


# --- rendering ---------------------------------------------------------------

def _stack_md(ptype: str, techs: List[str], evidence: List[str],
              prof: Optional[dict] = None) -> str:
    prof = prof or {}
    ev = ", ".join(evidence) if evidence else "none"
    tags = ", ".join(techs) if techs else "none"

    def line(label: str, key: str) -> str:
        items = prof.get(key) or []
        body = ", ".join(items) if items else "_(not detected — complete manually)_"
        return f"- **{label}:** {body}"

    detected = "\n".join((
        line("Languages & versions", "languages"),
        line("Frameworks", "frameworks"),
        line("Datastore(s)", "datastores"),
        line("Build / package manager", "build"),
        line("Testing", "testing"),
        line("Tooling (lint / format / containers)", "tooling"),
        line("Notable libraries", "libraries"),
    ))
    return f"""# Stack — {ptype}

Technologies this project uses. Agents read this so their `cdt library`
(RAG) queries are **project-aware**. Auto-filled from the manifests by
`cdt init/sync`; refine anything marked _not detected_.

## Detected
{detected}

## To complete (owner / Conductor)
- Architecture notes / constraints:
- External integrations / APIs:

<!-- detected tags: {tags} -->
<!-- detection evidence: {ev} -->
"""


def _roles_table(selected: List[str]) -> str:
    rows = ["| Role | Area | Skill |", "|------|------|-------|"]
    for slug in selected:
        r = roles_mod.ROLES[slug]
        rows.append(f"| `{slug}` | {r.area} | `{r.skill}` |")
    return "\n".join(rows)


def _project_memory(root: Path, limit: int = MEMORY_LIMIT) -> str:
    """Recent durable diary entries (decisions/solutions/errors/plans), newest first."""
    entries = []
    for jf in sorted(journal_dir(root).glob("*.jsonl")):
        for line in jf.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except ValueError:
                continue
            if e.get("kind") in MEMORY_KINDS:
                entries.append(e)
    if not entries:
        return "_No diary entries yet._"
    entries.sort(key=lambda e: e.get("ts", ""), reverse=True)
    lines = []
    for e in entries[:limit]:
        gate = f"gate {e['gate']}" if e.get("gate") is not None else "—"
        lines.append(f"- **[{gate}] {e.get('kind','')}** — {e.get('text','')}  "
                     f"_({e.get('ts','')})_")
    return "\n".join(lines)


def _render(root: Path, slug: str, ptype: str, selected: List[str]) -> str:
    tmpl = (TEMPLATES / "CLAUDE.md.tmpl").read_text(encoding="utf-8")
    flow = (TEMPLATES / "flow.md").read_text(encoding="utf-8")
    return (tmpl
            .replace("{project}", slug)
            .replace("{type}", ptype)
            .replace("{roles_table}", _roles_table(selected))
            .replace("{project_memory}", _project_memory(root))
            .replace("{flow}", flow))


def _managed_slice(text: str):
    """Returns (start, end) indices spanning the managed region (incl markers), or None."""
    s = text.find(MANAGED_START)
    e = text.find(MANAGED_END)
    if s == -1 or e == -1:
        return None
    return s, e + len(MANAGED_END)


def _write_claude_md(root: Path, slug: str, ptype: str, selected: List[str]) -> str:
    """Writes (init) or splices (sync) CLAUDE.md. Returns 'created' or 'synced'."""
    fresh = _render(root, slug, ptype, selected)
    out = root / "CLAUDE.md"
    if out.is_file():
        old = out.read_text(encoding="utf-8")
        old_span, new_span = _managed_slice(old), _managed_slice(fresh)
        if old_span and new_span:
            region = fresh[new_span[0]:new_span[1]]
            merged = old[:old_span[0]] + region + old[old_span[1]:]
            out.write_text(merged, encoding="utf-8")
            return "synced"
    out.write_text(fresh, encoding="utf-8")
    return "created"


# --- scaffolding -------------------------------------------------------------

def _copy_driver(project: Path) -> bool:
    """Install the `/cdt` flow-driver slash command into `.claude/commands/`.

    The driver is the interactive control loop (recall → RAG → delegate →
    record → user checkpoint) that makes the 11-gate flow actually enforced,
    instead of leaving it as passive CLAUDE.md guidance. Always overwritten so
    `sync` keeps it current. It is NOT a role skill, so it stays out of the
    36↔36 agent/skill parity.
    """
    src = TEMPLATES / "commands" / "cdt.md"
    if not src.is_file():
        return False
    dst = project / ".claude" / "commands"
    dst.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst / "cdt.md")
    return True


def _copy_roles(project: Path, selected: List[str]) -> int:
    agents_dst = project / ".claude" / "agents"
    skills_dst = project / ".claude" / "skills"
    agents_dst.mkdir(parents=True, exist_ok=True)
    skills_dst.mkdir(parents=True, exist_ok=True)
    n = 0
    for slug in selected:
        src_agent = TEMPLATES / "agents" / f"{slug}.md"
        if src_agent.is_file():
            shutil.copyfile(src_agent, agents_dst / f"{slug}.md")
        skill = roles_mod.ROLES[slug].skill
        src_skill = TEMPLATES / "skills" / skill / "SKILL.md"
        if src_skill.is_file():
            (skills_dst / skill).mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src_skill, skills_dst / skill / "SKILL.md")
        n += 1
    return n


def _resolve_selection(ptype: str, all_roles: bool, override: Optional[List[str]]):
    """Returns (selected, mode)."""
    if override:
        return roles_mod.select_roles(ptype, override=override), "custom"
    if all_roles:
        return roles_mod.select_roles(ptype, all_roles=True), "all"
    return roles_mod.select_roles(ptype), "subset"


def refresh_claude_md(root: Path) -> bool:
    """Best-effort live refresh of the managed region (called after journal writes)."""
    config = read_config(root)
    if config is None or not (root / "CLAUDE.md").is_file():
        return False
    selected = config.get("roles") or roles_mod.select_roles(config.get("type", "unknown"))
    try:
        _write_claude_md(root, config.get("project", root.name),
                         config.get("type", "unknown"), selected)
        return True
    except Exception:  # noqa: BLE001 — refresh is best-effort
        return False


# --- commands ----------------------------------------------------------------

def cmd_init(args) -> int:
    project = Path(args.path).resolve()
    if not project.is_dir():
        print(f"ERROR: not a directory: {project}", file=sys.stderr)
        return 2
    if config_path(project).is_file() and not args.force:
        print(f"Already enrolled: {config_path(project)} "
              "(use --force to re-init, or `cdt sync` to refresh)")
        return 0

    det_type, techs, evidence = detect(project)
    prof = profile(project)
    ptype = args.type or det_type
    slug = slugify(args.name or project.name)
    override = [s.strip() for s in args.roles.split(",")] if args.roles else None
    try:
        selected, mode = _resolve_selection(ptype, args.all, override)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    print(f"[1/4] analyzing {project.name}: type={ptype}"
          + (f", detected={', '.join(techs)}" if techs else ""))
    n = _copy_roles(project, selected)
    drv = _copy_driver(project)
    print(f"[2/4] .claude/: {n} agents + {n} skills ({mode} for {ptype})"
          + (" + /cdt driver" if drv else ""))

    stack_dir(project).mkdir(parents=True, exist_ok=True)
    leaves = _scaffold_memory_tree(project)
    (stack_dir(project) / f"{ptype}.md").write_text(
        _stack_md(ptype, techs, evidence, prof), encoding="utf-8")
    _ensure_memory_gitignore(project)
    write_config(project, {
        "project": slug, "type": ptype, "roles": selected, "roles_mode": mode,
        "honcho": {"workspace": slug, "base_url": args.honcho_url,
                   "session_prefix": "cdt"},
        "created": datetime.date.today().isoformat(),
    })
    register_project(project, slug, ptype)
    print(f"[3/4] .cdt/: enrolled '{slug}', stack -> {ptype}.md, "
          f"memory tree -> {leaves} folders")
    state = _write_claude_md(project, slug, ptype, selected)
    print(f"[4/4] CLAUDE.md {state} ({len(selected)} roles + memory + 11-gate flow)")
    print("Done. `cdt sync` keeps CLAUDE.md live as the project evolves.")
    return 0


def cmd_sync(args) -> int:
    root = Path(args.path).resolve() if args.path else find_project_root()
    config = read_config(root)
    if config is None:
        print(f"ERROR: not an enrolled project (no .cdt/ at {root}). "
              "Run `cdt init` first.", file=sys.stderr)
        return 2

    slug = config.get("project", slugify(root.name))
    mode = config.get("roles_mode", "subset")
    det_type, techs, evidence = detect(root)
    prof = profile(root)
    ptype = args.type or (det_type if det_type != "unknown" else config.get("type", "unknown"))

    if mode == "all":
        selected = roles_mod.select_roles(ptype, all_roles=True)
    elif mode == "custom":
        selected = config.get("roles") or roles_mod.select_roles(ptype)
    else:
        selected = roles_mod.select_roles(ptype)  # subset re-computed for current type

    n = _copy_roles(root, selected)
    _copy_driver(root)                    # keep the /cdt flow driver current
    leaves = _scaffold_memory_tree(root)  # ensure/upgrade the memory tree (idempotent)
    _ensure_memory_gitignore(root)
    migrated = _migrate_legacy_diary(root)  # pre-0.2.20 journal/ -> memory/diary/
    stack_dir(root).mkdir(parents=True, exist_ok=True)
    (stack_dir(root) / f"{ptype}.md").write_text(
        _stack_md(ptype, techs, evidence, prof), encoding="utf-8")
    config.update({"type": ptype, "roles": selected, "roles_mode": mode})
    write_config(root, config)
    register_project(root, slug, ptype)
    _auto_memory_sync(root, config)   # digest + ingest changed docs/records
    _write_memory_index(root)         # refresh the live map post-ingest
    state = _write_claude_md(root, slug, ptype, selected)

    tree_note = f", memory tree +{leaves} folders" if leaves else ""
    mig_note = f", migrated {migrated} legacy diary file(s)" if migrated else ""
    print(f"synced '{slug}' (type={ptype}, {n} roles): stack refreshed, "
          f"diary memory pulled{tree_note}{mig_note}, CLAUDE.md {state}.")
    return 0


def main(argv: List[str]) -> int:
    force_utf8()
    # Dispatched as `cdt init ...` / `cdt sync ...`; the
    # action word is argv[0] when present, else default to init.
    action = "init"
    rest = argv
    if argv and argv[0] in ("init", "sync"):
        action, rest = argv[0], argv[1:]

    ap = argparse.ArgumentParser(prog=f"cdt {action}")
    ap.add_argument("path", nargs="?", default=None if action == "sync" else ".",
                    help="project directory")
    ap.add_argument("--type", choices=VALID_TYPES, help="force the project type")
    if action == "init":
        ap.add_argument("--name", help="project name (default: directory name)")
        ap.add_argument("--all", action="store_true", help="scaffold all 36 roles")
        ap.add_argument("--roles", help="comma-separated role slugs (override the subset)")
        ap.add_argument("--honcho-url", default=DEFAULT_HONCHO_URL, help="Honcho base URL")
        ap.add_argument("--force", action="store_true", help="re-init (overwrite)")
    args = ap.parse_args(rest)

    return cmd_sync(args) if action == "sync" else cmd_init(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
