"""OpenCode target — near-parity with Claude Code via OpenCode's native layout.

Projects into:
  .opencode/agents/<role>.md         role agents (frontmatter translated:
                                     `mode: subagent`, model tier mapped)
  .opencode/skills/<skill>/SKILL.md  matching skills (copied as-is)
  .opencode/commands/cdt.md          the `/cdt` flow driver (OpenCode flavor)
  .opencode/plugins/conductor-honcho.js  live-memory hook (recall injection)
  opencode.json                      `instructions` registers AGENTS.md
  AGENTS.md                          the project guide

OpenCode uses plural subdir names (`agents/`, `commands/`, ...); singular is
back-compat. Model ids use `provider/model-id`; the tier map below is editable.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Dict, List

from .. import roles as roles_mod
from . import base
from .base import GuideContext, TEMPLATES

# Our agent templates declare a coarse tier (opus/sonnet/haiku). OpenCode wants a
# fully-qualified `provider/model-id`. These are the current Anthropic ids; edit
# them (or the per-agent `model:` line) if your OpenCode provider catalog differs.
MODEL_MAP: Dict[str, str] = {
    "opus": "anthropic/claude-opus-4-8",
    "sonnet": "anthropic/claude-sonnet-4-6",
    "haiku": "anthropic/claude-haiku-4-5-20251001",
}

HONCHO_PLUGIN = """\
// Conductor live-memory plugin for OpenCode — recall + capture.
// Generated by `cdt`; edit freely — `cdt sync` will not overwrite an edited copy.
export const ConductorHoncho = async ({ $ }) => {
  return {
    // Recall: surface what this project already decided/learned.
    "session.created": async () => {
      try { await $`cdt journal context`; } catch (_) {}
    },
    // Capture: `chat.message` fires when a user message is received; its parts
    // carry the typed text. We append it to local memory (zero network). Bun's
    // `$` escapes the interpolated arg, so arbitrary prompt text is safe. If a
    // given OpenCode version doesn't support this hook, the key is ignored — the
    // plugin still loads and recall keeps working.
    "chat.message": async (_input, output) => {
      try {
        const parts = (output && output.parts) || [];
        const text = parts
          .filter((p) => p && p.type === "text")
          .map((p) => p.text)
          .join("\\n")
          .trim();
        if (text) await $`cdt journal observe --text ${text}`;
      } catch (_) {}
    },
  };
};
"""


class OpenCodeTarget:
    key = "opencode"
    label = "OpenCode"

    def detect(self, project: Path) -> bool:
        return ((project / ".opencode").is_dir()
                or (project / "opencode.json").is_file()
                or (project / "opencode.jsonc").is_file())

    def guide_path(self, project: Path) -> Path:
        return project / "AGENTS.md"

    def emit_roles(self, project: Path, selected: List[str]) -> int:
        agents_dst = project / ".opencode" / "agents"
        skills_dst = project / ".opencode" / "skills"
        agents_dst.mkdir(parents=True, exist_ok=True)
        skills_dst.mkdir(parents=True, exist_ok=True)
        n = 0
        for slug in selected:
            src_agent = TEMPLATES / "agents" / f"{slug}.md"
            if src_agent.is_file():
                meta, body = base.split_frontmatter(
                    src_agent.read_text(encoding="utf-8"))
                (agents_dst / f"{slug}.md").write_text(
                    base.join_frontmatter(self._agent_meta(meta), body),
                    encoding="utf-8")
            skill = roles_mod.ROLES[slug].skill
            src_skill = TEMPLATES / "skills" / skill / "SKILL.md"
            if src_skill.is_file():
                (skills_dst / skill).mkdir(parents=True, exist_ok=True)
                shutil.copyfile(src_skill, skills_dst / skill / "SKILL.md")
            n += 1
        return n

    @staticmethod
    def _agent_meta(meta: Dict[str, str]) -> Dict[str, str]:
        """Translate Claude agent frontmatter to OpenCode's dialect.

        The filename carries the agent name, so `name` is dropped. `mode:
        subagent` makes it an @-mentionable specialist; the coarse model tier is
        mapped to a `provider/model-id` when known (else omitted, leaving the
        OpenCode default).
        """
        out: Dict[str, str] = {}
        if "description" in meta:
            out["description"] = meta["description"]
        out["mode"] = "subagent"
        tier = meta.get("model", "").strip()
        if tier in MODEL_MAP:
            out["model"] = MODEL_MAP[tier]
        return out

    def emit_driver(self, project: Path) -> bool:
        src = TEMPLATES / "commands" / "cdt.opencode.md"
        if not src.is_file():
            return False
        dst = project / ".opencode" / "commands"
        dst.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst / "cdt.md")
        return True

    def emit_hooks(self, project: Path) -> int:
        """Install the live-memory plugin (recall injection at session start).

        Written once; never overwrites a copy the user has edited, so the
        `message.updated` capture TODO can be filled in without `cdt sync`
        clobbering it.
        """
        dst = project / ".opencode" / "plugins" / "conductor-honcho.js"
        if dst.is_file():
            return 0
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(HONCHO_PLUGIN, encoding="utf-8")
        return 1

    def emit_automations(self, project: Path) -> int:
        text = base.automation_text("triage")
        if text is None:
            return 0
        dst = project / ".opencode" / "commands"
        dst.mkdir(parents=True, exist_ok=True)
        (dst / "cdt-triage.md").write_text(text, encoding="utf-8")
        return 1

    def emit_mcp(self, project: Path) -> int:
        """Register MCP connectors under `opencode.json`'s `mcp` key.

        OpenCode supports a per-server `enabled` boolean, so all connectors are
        emitted — `conductor` enabled, the third-party stubs disabled — and the
        user just flips a flag (and fills the env) to wire one in. Merged into any
        existing config without disturbing other keys or servers (mirrors
        `_register_instructions`); a server already present is left untouched.
        """
        cfg = project / "opencode.json"
        data: dict = {}
        if cfg.is_file():
            try:
                data = json.loads(cfg.read_text(encoding="utf-8"))
            except (ValueError, OSError):
                return 0  # don't clobber an unparseable (e.g. jsonc) config
        if not isinstance(data, dict):
            return 0
        mcp = data.get("mcp")
        if not isinstance(mcp, dict):
            mcp = {}
        added = False
        for name, c in base.CONNECTORS.items():
            if name in mcp:                       # merge-not-clobber: keep user's entry
                continue
            mcp[name] = {
                "type": "local",
                "command": [c["command"], *c["args"]],
                "environment": c["env"],
                "enabled": bool(c.get("enabled")),
            }
            added = True
        if not added and cfg.is_file():
            return 0
        data["mcp"] = mcp
        data.setdefault("$schema", "https://opencode.ai/config.json")
        cfg.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")
        return 1

    def emit_guide(self, ctx: GuideContext) -> str:
        state = base.write_guide(ctx.root / "AGENTS.md", ctx, "AGENTS.md.tmpl")
        self._register_instructions(ctx.root)
        return state

    @staticmethod
    def _register_instructions(project: Path) -> None:
        """Ensure opencode.json's `instructions` array loads AGENTS.md.

        Merges into any existing config without disturbing other keys; creates a
        minimal config if none exists.
        """
        cfg = project / "opencode.json"
        data: dict = {}
        if cfg.is_file():
            try:
                data = json.loads(cfg.read_text(encoding="utf-8"))
            except (ValueError, OSError):
                return  # don't clobber an unparseable (e.g. jsonc) config
        if not isinstance(data, dict):
            return
        instr = data.get("instructions")
        if not isinstance(instr, list):
            instr = []
        if "AGENTS.md" not in instr:
            instr.append("AGENTS.md")
        data["instructions"] = instr
        data.setdefault("$schema", "https://opencode.ai/config.json")
        cfg.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")
