"""Pi target (pi.dev) — roles as native skills, `/cdt` prompt, full live memory.

Pi is a minimal harness: AGENTS.md + skills + prompt templates + TypeScript
extensions, no subagents/MCP. Projects into:
  .pi/skills/<skill>/SKILL.md        role skills (folded persona + steps)
  .pi/prompts/cdt.md                 the `/cdt` flow driver (prompt template)
  .pi/extensions/conductor-honcho.ts live memory — BOTH halves (Pi's `input`
                                     event gives the prompt text, so capture
                                     works here where OpenCode could only recall)
  AGENTS.md                          the project guide (Pi loads it from cwd)
"""
from __future__ import annotations

import shutil
from pathlib import Path
from typing import List

from . import base
from .base import GuideContext, TEMPLATES

# Pi extension: recall on session start + capture on every user input. Pi's
# `input` event carries the raw text, so `cdt journal observe --text` mirrors the
# Claude UserPromptSubmit hook exactly. Both calls are best-effort and never
# block the turn.
HONCHO_EXT = """\
// Conductor live-memory extension for Pi (pi.dev).
// Generated by `cdt`; edit freely — `cdt sync` will not overwrite an edited copy.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  // Recall: surface what this project already decided/learned.
  pi.on("session_start", async (_event, _ctx) => {
    try { await pi.exec("cdt", ["journal", "context"]); } catch (_) {}
  });
  // Capture: append the owner's prompt to local memory (zero network).
  pi.on("input", async (event, _ctx) => {
    try { await pi.exec("cdt", ["journal", "observe", "--text", event.text]); } catch (_) {}
    return { action: "continue" };
  });
}
"""


class PiTarget:
    key = "pi"
    label = "Pi"

    def detect(self, project: Path) -> bool:
        return (project / ".pi").is_dir()

    def guide_path(self, project: Path) -> Path:
        return project / "AGENTS.md"

    def emit_roles(self, project: Path, selected: List[str]) -> int:
        skills_dst = project / ".pi" / "skills"
        skills_dst.mkdir(parents=True, exist_ok=True)
        n = 0
        for slug in selected:
            merged = base.merge_role_skill(slug)
            if merged is None:
                continue
            skill_slug, description, body = merged
            (skills_dst / skill_slug).mkdir(parents=True, exist_ok=True)
            (skills_dst / skill_slug / "SKILL.md").write_text(
                base.join_frontmatter({"name": skill_slug, "description": description}, body),
                encoding="utf-8")
            n += 1
        return n

    def emit_driver(self, project: Path) -> bool:
        src = TEMPLATES / "commands" / "cdt.pi.md"
        if not src.is_file():
            return False
        dst = project / ".pi" / "prompts"
        dst.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst / "cdt.md")
        return True

    def emit_hooks(self, project: Path) -> int:
        dst = project / ".pi" / "extensions" / "conductor-honcho.ts"
        if dst.is_file():
            return 0
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(HONCHO_EXT, encoding="utf-8")
        return 1

    def emit_guide(self, ctx: GuideContext) -> str:
        return base.write_guide(ctx.root / "AGENTS.md", ctx, "AGENTS.md.tmpl")
